version: '3'

services:
  app:
    build: .
    image: developer-portal-backend
    ports:
      - 9999:9999
    volumes:
      - .:/home/node
      - notused:/home/node/node_modules
    command: npm run watch
  test:
    build: .
    image: developer-portal-backend
    command: npm test
volumes:
  notused:
