version: '3'

services:
  app:
    build: .
    image: developer-portal-backend
    ports:
      - 9999:9999
    volumes:
      # map local to remote folder, exclude node_modules
      - .:/home/node
      - /home/node/node_modules
    command: npm run watch
