version: '3.7'

services:
  app:
    build:
      context: .
      target: base
    image: developer-portal-backend
    ports:
      - 9999:9999
      # Debug port
      - 9229:9229
    volumes:
      # map local to remote folder, exclude node_modules
      - .:/home/node
      - /home/node/node_modules
    command: npm run ${RUN_COMMAND:-watch}
    # Debug command
    # command: npm run watch:debug
    depends_on:
      - tyk-gateway
    restart: on-failure
    env_file: '.env'

  tyk-gateway:
    image: tykio/tyk-gateway:latest
    ports:
    - "7070:8080"
    networks:
    - tyk
    depends_on:
      - tyk-redis
    volumes:
    - ./config/tyk.conf:/opt/tyk-gateway/tyk.conf
    - ./apps/:/opt/tyk-gateway/apps
  tyk-redis:
    image: redis:latest
    ports:
    - "6379:6379"
    volumes:
    - redis-data:/data
    networks:
    - tyk

  dynamodb:
    image: amazon/dynamodb-local
    ports:
      - 8080:8000
  dynamodb-migration:
    image: developer-portal-backend
    env_file: '.env'
    depends_on:
      - dynamodb
    command: node dev/dynamodb_schema.js
    
  mock:
    build:
      context: dev/mocks/
    image: developer-portal-services-mock
    ports:
      - 3002:3001
    volumes:
      - ./dev/mocks:/home/node
      - /home/node/node_modules
    command: node json-mocks

volumes:
  redis-data:

networks:
  tyk: