version: 0.2

env:
  git-credential-helper: yes
  parameter-store:
    GITHUB_TOKEN: "/dvp/devops/va_bot_github_token"
phases:
  pre_build:
    commands:
    - |
      npm install -g semantic-release \
      @semantic-release/changelog \
      @semantic-release/commit-analyzer \
      @semantic-release/exec \
      @semantic-release/git \
      @semantic-release/release-notes-generator
  build:
    commands:
      - |-
          if [ "$DRY_RUN" == "true" ]; then
            npx semantic-release --dry-run
          else
            npx semantic-release --ci true
          fi
  post_build:
    commands:
