version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - apt-get install -y curl
      - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
      - nvm install node 12.16.1
      - nvm alias default 12.16.1
  pre_build:
    commands:
    - |
      npm install -g semantic-release \
      @semantic-release/changelog \
      @semantic-release/commit-analyzer \
      @semantic-release/exec \
      @semantic-release/git \
      @semantic-release/release-notes-generator
  build:
    env:
      - parameter_store:
        GITHUB_TOKEN: "/dvp/devops/va_bot_github_token"
    commands:
      - npx -p node@12 semantic-release --dry-run
  post_build:
    commands:
