version: 0.2

env:
  git-credential-helper: yes

phases:
  pre_build:
    commands:
    - |
      npm install -g semantic-release \
      @semantic-release/changelog \
      @semantic-release/commit-analyzer \
      @semantic-release/exec \
      @semantic-release/git \
      @semantic-release/release-notes-generator
  build:
    commands:
      - npx semantic-release --dry-run
  post_build:
    commands:
