version: 0.2

env:
  git-credential-helper: yes
  parameter-store:
    GITHUB_TOKEN: "/dvp/devops/va_bot_github_token"
phases:
  install:
    commands:
    - apt update
    - apt-get -y install awscli jq
    - curl -LOk https://github.com/awslabs/fargatecli/releases/download/0.3.2/fargate-0.3.2-linux-amd64.zip
    - unzip fargate-0.3.2-linux-amd64.zip
  pre_build:
    commands:
    - echo Logging into ECR
    - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
    - |
      npm install -g semantic-release \
      @semantic-release/changelog \
      @semantic-release/commit-analyzer \
      @semantic-release/exec \
      @semantic-release/git \
      @semantic-release/release-notes-generator \
      semantic-release-slack-bot
  build:
    commands:
      - npx semantic-release --ci true
  post_build:
    commands:
