_format_version: "1.1"
services:
- connect_timeout: 60000
  host: localhost
  id: 4027841a-9f33-4692-b1f2-841d93905ce9
  path: /consumers
  port: 8001
  protocol: http
  read_timeout: 60000
  retries: 5
  write_timeout: 60000
  routes:
  - id: 1880f41d-7fe9-49c2-8afd-d550825146bb
    methods:
    - POST
    - GET
    paths:
    - /internal/admin/consumers
    preserve_host: false
    protocols:
    - http
    regex_priority: 0
    strip_path: true
    https_redirect_status_code: 426
- connect_timeout: 60000
  host: localhost
  id: 900dd6c8-700f-4a7c-9b2e-73f80ed14da4
  path: /consumers
  port: 8001
  protocol: http
  read_timeout: 60000
  retries: 5
  write_timeout: 60000
  routes:
  - id: 9c2f0908-4bb9-4000-acc9-d9e7279d4b7e
    methods:
    - POST
    - GET
    paths:
    - /internal/admin/consumers
    preserve_host: false
    protocols:
    - http
    regex_priority: 0
    strip_path: true
    https_redirect_status_code: 426
- connect_timeout: 60000
  host: cat-fact.herokuapp.com
  name: cats
  port: 80
  protocol: http
  read_timeout: 60000
  retries: 2
  write_timeout: 60000
  routes:
  - name: cats
    paths:
    - /meow
    preserve_host: false
    protocols:
    - http
    - https
    regex_priority: 0
    strip_path: true
    https_redirect_status_code: 426
- connect_timeout: 60000
  host: randomfox.ca
  name: fox
  port: 80
  protocol: http
  read_timeout: 60000
  retries: 2
  write_timeout: 60000
  routes:
  - name: fox-image
    paths:
    - /fox
    preserve_host: false
    protocols:
    - http
    - https
    regex_priority: 0
    strip_path: true
    https_redirect_status_code: 426
    plugins:
      - name: acl
        config:
          blacklist: null
          hide_groups_header: true
          whitelist: 
            - test-users
            - guacamole-fans
        enabled: true
        run_on: first
        protocols:
        - http
        - https
- connect_timeout: 60000
  host: official-joke-api.appspot.com
  name: jokes
  port: 80
  protocol: http
  read_timeout: 60000
  retries: 2
  write_timeout: 60000
  routes:
  - name: random-joke
    paths:
    - /joke
    preserve_host: false
    protocols:
    - http
    - https
    regex_priority: 0
    strip_path: true
    https_redirect_status_code: 426
    plugins:
    - name: acl
      config:
        blacklist: null
        hide_groups_header: true
        whitelist: 
          - test-users
      enabled: true
      run_on: first
      protocols:
      - http
      - https
consumers:
- username: _internal_DeveloperPortal
  keyauth_credentials:
  - key: taco
- username: bob
  keyauth_credentials:
  - key: burrito
  acls:
  - group: test-users
- username: karen
  keyauth_credentials:
  - key: enchilada
  acls:
  - group: test-users
- username: frank
  keyauth_credentials:
  - key: guacamole
  acls:
  - group: guacamole-fans
plugins:
- name: key-auth
  config:
    anonymous: null
    hide_credentials: false
    key_in_body: false
    key_names:
    - apikey
    run_on_preflight: true
  enabled: true
  run_on: first
  protocols:
  - http
  - https