_format_version: "1.1"
services:
- connect_timeout: 60000
  host: localhost
  id: 4027841a-9f33-4692-b1f2-841d93905ce9
  path: /consumers
  port: 8001
  protocol: http
  read_timeout: 60000
  retries: 5
  write_timeout: 60000
  routes:
  - id: 1880f41d-7fe9-49c2-8afd-d550825146bb
    methods:
    - POST
    - GET
    paths:
    - /internal/admin/consumers
    preserve_host: false
    protocols:
    - http
    regex_priority: 0
    strip_path: true
    https_redirect_status_code: 426
- connect_timeout: 60000
  host: localhost
  id: 900dd6c8-700f-4a7c-9b2e-73f80ed14da4
  path: /consumers
  port: 8001
  protocol: http
  read_timeout: 60000
  retries: 5
  write_timeout: 60000
  routes:
  - id: 9c2f0908-4bb9-4000-acc9-d9e7279d4b7e
    methods:
    - POST
    - GET
    paths:
    - /internal/admin/consumers
    preserve_host: false
    protocols:
    - http
    regex_priority: 0
    strip_path: true
    https_redirect_status_code: 426
consumers:
- username: _internal_DeveloperPortal
  keyauth_credentials:
  - key: taco
plugins:
- name: key-auth
  config:
    anonymous: null
    hide_credentials: false
    key_in_body: false
    key_names:
    - apikey
    run_on_preflight: true
  enabled: true
  run_on: first
  protocols:
  - http
  - https
